/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({
    enabled: true,
	 paths : {
      'MyApp3.store' : 'js/firstPage/app/store',
      'MyApp3.view' : 'js/firstPage/app/view'
   }
});

Ext.require(['MyApp3.store.MenuStore','MyApp3.view.cs_MyViewport']);

Ext.application({
    stores: [
        'MenuStore'
    ],
    views: [
        'cs_MyViewport'
    ],
    name: 'MyApp3',

    launch: function() {
        Ext.create('MyApp3.view.cs_MyViewport');
    }

});
